FROM node:22-alpine AS build

WORKDIR /app

COPY package.json ./
COPY packages ./packages

RUN pnpm install

COPY tsconfig.json vite.config.ts ./
COPY scripts ./scripts
COPY src ./src

RUN pnpm run build

FROM nginx:stable-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/web /usr/share/nginx/html

EXPOSE 80